{% set name = "types-DateTimeRange" %}
{% set version = "2.0.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types-DateTimeRange-{{ version }}.tar.gz
  sha256: a173c317691f0c98f4d86a8e2c9691550994be9c598ed7d8b8a6c6057a7e754c

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - types-python-dateutil

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f $SP_DIR/datetimerange-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for DateTimeRange
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
