{% set name = "types-DateTimeRange" %}
{% set version = "1.2.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-DateTimeRange-{{ version }}.tar.gz
  sha256: 3f084166e5772439e31e43ff6cb9a605c40dfa7143ff34ce88ce4fb645fa391d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - types-python-dateutil

test:
  commands:
    - test -f $SP_DIR/datetimerange-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for DateTimeRange
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
