{% set name = "types-DateTimeRange" %}
{% set version = "2.0.0.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-DateTimeRange-{{ version }}.tar.gz
  sha256: ed42cce6120a21ccd7551549ba099f67c347bdd04dc22b40639480cb124aee1e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - types-python-dateutil

test:
  commands:
    - test -f $SP_DIR/datetimerange-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for DateTimeRange
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
